export const foodCategories = [
  {
    category: "leafy_greens",
    displayName: "Leafy Greens",
    keywords: [
      "SPINACH",
      "LETTUCE",
      "SALAD",
      "KALE",
      "CHINAKOHL",
      "CABBAGE",
      "ROMAINE",
      "ARUGULA",
      "PAK CHOI",
      "BOK CHOY",
      "CELERY",
      "ENDIVE",
      "WATERCRESS",
    ],
  },

  {
    category: "berries",
    displayName: "Strawberry",
    keywords: [
      "ERDBEERE",
      "STRAWBERRY",
      "BLUEBERRY",
      "RASPBERRY",
      "BLACKBERRY",
      "CRANBERRY",
      "BERRY",
    ],
  },

  {
    category: "fresh_fish",
    displayName: "Salmon",
    keywords: [
      "LACHS",
      "SALMON",
      "TUNA",
      "COD",
      "SHRIMP",
      "PRAWN",
      "FISH",
      "SARDINE",
      "MACKEREL",
      "SEAFOOD",
      "TILAPIA",
      "TROUT",
      "CRAB",
      "LOBSTER",
      "MUSSEL",
    ],
  },

  {
    category: "fresh_meat",
    displayName: "Chicken",
    keywords: [
      "CHICKEN",
      "BEEF",
      "PORK",
      "TURKEY",
      "HAM",
      "SAUSAGE",
      "BACON",
      "LAMB",
      "DUCK",
      "MINCE",
      "STEAK",
      "MEAT",
      "SALAMI",
    ],
  },

  {
    category: "dairy",
    displayName: "Yogurt",
    keywords: [
      "MILK",
      "JOGHURT",
      "YOGURT",
      "CHEESE",
      "BUTTER",
      "CREAM",
      "NATURJOGHURT",
      "MOZZARELLA",
      "CHEDDAR",
      "PARMESAN",
      "FETA",
      "RICOTTA",
      "SKYR",
      "KEFIR",
    ],
  },

  {
    category: "eggs",
    displayName: "Egg",
    keywords: [
      "EGG",
      "EIER",
      "EI",
      "OMELETTE",
      "SCRAMBLED EGG",
    ],
  },

  {
    category: "tomatoes",
    displayName: "Tomato",
    keywords: [
      "TOMATE",
      "TOMATO",
      "RISPENTOMATE",
      "CHERRY TOMATO",
      "PLUM TOMATO",
    ],
  },

  {
    category: "root_vegetables",
    displayName: "Potato",
    keywords: [
      "POTATO",
      "KARTOFFEL",
      "CARROT",
      "ONION",
      "GARLIC",
      "BEETROOT",
      "RADISH",
      "TURNIP",
      "SWEET POTATO",
      "GINGER",
      "PARSNIP",
    ],
  },

  {
    category: "spring_onion",
    displayName: "Spring Onion",
    keywords: [
      "LAUCHZWIEBEL",
      "LAUCHZWIEBELN",
      "LAUCHZWIÉBEL",
      "LAUCHZWIÉBELN",
      "SPRING ONION",
      "SCALLION",
      "GREEN ONION",
      "CHIVE",
    ],
  },

  {
    category: "fruit",
    displayName: "Fruit",
    keywords: [
      "APPLE",
      "BANANA",
      "ORANGE",
      "PEAR",
      "MANGO",
      "GRAPE",
      "KIWI",
      "PEACH",
      "PINEAPPLE",
      "LEMON",
      "LIME",
      "MELON",
      "WATERMELON",
      "AVOCADO",
      "PLUM",
      "APRICOT",
      "FIG",
    ],
  },

  {
    category: "vegetables",
    displayName: "Vegetable",
    keywords: [
      "BROCCOLI",
      "CAULIFLOWER",
      "ZUCCHINI",
      "CUCUMBER",
      "PEPPER",
      "PAPRIKA",
      "MUSHROOM",
      "AUBERGINE",
      "EGGPLANT",
      "CORN",
      "PEAS",
      "BEAN",
    ],
  },

  {
    category: "bread_bakery",
    displayName: "Bread",
    keywords: [
      "BREAD",
      "BUN",
      "CROISSANT",
      "TOAST",
      "BAGEL",
      "CAKE",
      "MUFFIN",
      "DONUT",
      "PIZZA",
      "WRAP",
      "TORTILLA",
      "SANDWICH",
      "ROLL",
    ],
  },

  {
    category: "rice_grains",
    displayName: "Rice",
    keywords: [
      "RICE",
      "PASTA",
      "NOODLE",
      "OATS",
      "QUINOA",
      "CEREAL",
      "SPAGHETTI",
      "MACARONI",
      "COUSCOUS",
      "BULGUR",
      "BARLEY",
    ],
  },

  {
    category: "frozen_food",
    displayName: "Frozen Food",
    keywords: [
      "FROZEN",
      "ICE CREAM",
      "FROZEN PIZZA",
      "FROZEN VEG",
      "FROZEN FRIES",
      "FROZEN BERRY",
    ],
  },

  {
    category: "canned_food",
    displayName: "Canned Food",
    keywords: [
      "CANNED",
      "BEANS",
      "TUNA CAN",
      "CORN CAN",
      "SOUP",
      "CHICKPEA",
      "LENTIL",
      "TOMATO CAN",
    ],
  },

  {
    category: "snacks",
    displayName: "Snack",
    keywords: [
      "CHIPS",
      "COOKIE",
      "CHOCOLATE",
      "CRACKER",
      "SNACK",
      "BISCUIT",
      "POPCORN",
      "CANDY",
      "NUTS",
      "ALMOND",
      "CASHEW",
    ],
  },

  {
    category: "beverages",
    displayName: "Drink",
    keywords: [
      "JUICE",
      "COLA",
      "WATER",
      "COFFEE",
      "TEA",
      "SODA",
      "SMOOTHIE",
      "ENERGY DRINK",
      "LEMONADE",
      "LATTE",
      "ESPRESSO",
      "CAPPUCCINO",
    ],
  },

  {
    category: "sauces_condiments",
    displayName: "Sauce",
    keywords: [
      "KETCHUP",
      "MAYO",
      "MUSTARD",
      "SOY SAUCE",
      "HOT SAUCE",
      "PESTO",
      "CURRY PASTE",
      "DRESSING",
      "VINEGAR",
    ],
  },

  {
    category: "spices",
    displayName: "Spice",
    keywords: [
      "SALT",
      "PEPPER",
      "PAPRIKA POWDER",
      "CURRY",
      "OREGANO",
      "BASIL",
      "CINNAMON",
      "SPICE",
      "HERB",
    ],
  },
];